[project]
name = "emg-bids-converter"
version = "0.1.0"
description = "Open-source Python package for converting EMG recordings from proprietary formats to the BIDS standard."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Hugo Haffad" }]
requires-python = ">=3.12"
dependencies = [
    "bidsschematools>=1.2.7",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]